### PR TITLE
Update servo-fontconfig, core-text, and core-foundation.

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by jdm** [comment]
I've noticed https://github.com/matprec/rust-font-loader/pull/27 and I'll try to figure out what's going on there.

**Comment by jdm** [comment]
Hmm, I wonder why there's no TravisCI job started yet.

**Comment by matprec** [comment]
Don't know either... but in the UI it is green: https://travis-ci.org/github/matprec/rust-font-loader

Thank you!

**Comment by jdm** [comment]
Thanks! Will you be releasing a new version soon?

**Comment by matprec** [comment]
Oh sure, thanks for the reminder :D Just published, should be available any minute

**Pull request merged**
